name: Build and Publish Docker Image to Docker Hub

on:
  push:
    branches:
      - master

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}


    - name: Build the Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/imagegenerator-client:latest .


    - name: Tag the image with commit SHA
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/imagegenerator-client:latest ${{ secrets.DOCKER_USERNAME }}/imagegenerator-client:${{ github.sha }}

    - name: Push the Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/imagegenerator-client:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/imagegenerator-client:${{ github.sha }}
